record:
    path: "."
    command: "sudo docker compose -f docker-compose.yml -f docker-compose.without-nginx.yml up"
    proxyport: 16789
    containerName: "docker-mattermost-1"
    networkName: ""
    delay: 200
    buildDelay: 2m
    passThroughPorts: []
    filters:
        ReqHeader: []
        urlMethods: {}

test:
    path: "."
    command: "sudo docker compose -f docker-compose.yml -f docker-compose.without-nginx.yml up"
    proxyport: 16789
    containerName: "docker-mattermost-1"
    networkName: ""
    tests: {}
    globalNoise:
        global:
            body: {}
            # Add body fields here to ignore dynamic content
            header: {
                    "Date": [], # Ignore Date header as it changes
                    "X-Request-Id": [], # Ignore Request ID
                    "X-Version-Id": [], # Ignore Version ID
                    "X-Frame-Options": [], # Example of another header to ignore
                    "Set-Cookie": [], # Ignore Set-Cookie header
                    # Add other dynamic headers here to be ignored
                }

    delay: 200
    buildDelay: 30s
    apiTimeout: 5
    passThroughPorts: []
    withCoverage: true
    coverageReportPath: "."

    # Example on using globalNoise
    # globalNoise:
    #    global:
    #      body: {
    #         # to ignore some values for a field,
    #         # pass regex patterns to the corresponding array value
    #         "url": ["https?://\S+", "http://\S+"],
    #      }
    #      header: {
    #         # to ignore the entire field, pass an empty array
    #         "Date": [],
    #         "X-Request-Id": [],
    #         "X-Version-Id": []  # Uncomment or add this line if needed
    #       }
    #     # to ignore fields or the corresponding values for a specific test-set,
    #     # pass the test-set-name as a key to the "test-sets" object and
    #     # populate the corresponding "body" and "header" objects
    #     test-sets:
    #       test-set-1:
    #         body: {
    #           # ignore all the values for the "url" field
    #           "url": []
    #         }
    #         header: {
    #           # we can also pass the exact value to ignore for a field
    #           "User-Agent": ["PostmanRuntime/7.34.0"]
    #         }
